import type { Metadata } from 'next'
import AdminSidebar from '@/components/layout/admin/AdminSidebar'
import AdminHeader from '@/components/layout/admin/AdminHeader'
import { auth } from '@/lib/auth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { slug?: string[] }
}>) {
  const session = await auth()
  const segment = params.slug?.[0] ?? null

  return (
    <div className="flex h-screen w-full bg-neutral-950 text-zinc-300 antialiased font-sans overflow-hidden">
      <AdminSidebar segment={segment} />
      <main className="flex-1 flex flex-col h-screen overflow-hidden bg-black/20 relative rounded-l-[3rem] px-8 md:px-12">
        <AdminHeader title="Overview" subtitle={`Hello ${session?.user?.name}, here's your daily comics update.`} />
        {children}
      </main>
    </div>
  )
}
